version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    command: node server.js
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
